election/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('vote.urls', namespace='vote'), ),
]

vote/urls.py
from django.conf.urls import url
from vote.views import (
	landing_view, login_view, register_view, logout_view, post_candidates, candidates_detail, 
	staff_view, user_view, candidates, candidates_update, candidate_deleted,
	candidate_delete_confirmation,user_info,user_info_update, view_candidates,
	post_election,election_detail, elections, election_update, view_candidates_detail,
	user_elections, user_election_detail, user_vote_success, election_delete_confirmation,
	election_deleted)
	# user_results_view, user_polls_view)

from django.conf import settings 
from django.conf.urls.static import static

from . import views


urlpatterns = [
	url(r'^$', landing_view, name='landing'),
	url(r'^login/$', login_view, name='login'),
	url(r'^logout/$', logout_view, name='logout'),
	url(r'^admin/staff/(?P<username>[a-z]+)/$', staff_view, name="welcome_staff"),
	url(r'user/(?P<u_id>\d+)/$', user_view, name="welcome_user"),
	url(r'^register/$', register_view, name='register'),
	url(r'^admin/post_candidates/$',post_candidates, name='post_candidates'),
	url(r'^candidates_detail/(?P<c_id>\d+)/', candidates_detail, name='candidates_detail'),
	url(r'^admin/candidates_list/$', candidates, name="candidates_list" ),
	url(r'^admin/candidates/(?P<c_id>\d+)/edit/$', candidates_update , name="candidates_update"),
	url(r'^admin/candidates/(?P<c_id>\d+)/delete/$', candidate_delete_confirmation , name="candidate_delete_confirmation"),
	url(r'^admin/candidates/(?P<c_id>\d+)/delete_success/$', candidate_deleted , name="candidate_deleted"),
	url(r'^admin/post_election/$', post_election, name='post_election'),
	url(r'^admin/election_detail/(?P<e_id>\d+)/', election_detail, name='election_detail'),
	url(r'^admin/elections/(?P<e_id>\d+)/edit/$', election_update , name="election_update"),
	url(r'^admin/elections/(?P<e_id>\d+)/delete/$', election_delete_confirmation , name="election_delete_confirmation"),
	url(r'^admin/elections/(?P<e_id>\d+)/delete_success/$', election_deleted , name="election_deleted"),
	url(r'^admin/elections_form_list/$', elections, name="elections_list" ),
	url(r'^user/(?P<u_id>\d+)/profile/$', user_info, name="user_info"),
	url(r'^user/(?P<u_id>\d+)/edit/$', user_info_update, name="user_info_update"),
	url(r'^user/(?P<u_id>\d+)/view_candidates/$', view_candidates, name='view_candidates'),
	url(r'^user/(?P<u_id>\d+)/candidates_detail/(?P<c_id>\d+)/$', view_candidates_detail, name='view_candidates_detail'),
	url(r'^user/(?P<u_id>\d+)/elections/$', user_elections, name="user_elections_list"),
	url(r'^user/(?P<u_id>\d+)/election_detail/(?P<e_id>\d+)/', user_election_detail, name='user_election_detail'),
	url(r'^user/(?P<u_id>\d+)/election_detail/(?P<e_id>\d+)/success', user_vote_success, name='user_vote_success'),
	# url(r'^user/(?P<u_id>\d+)/results/$', user_results_view, name="user_results"),

	#for voting
	url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
	url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
	url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
	url(r'^user/(?P<u_id>\d+)/poll_list/$', views.poll_list, name="poll_list"),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

vote/models.py
from django.db import models
from django.core.urlresolvers import reverse
import datetime
from multiselectfield import MultiSelectField
from django.utils import timezone


class Candidates(models.Model):
	c_id = models.AutoField(primary_key=True)
	first_name = models.CharField(max_length=30)
	#middle_name = models.CharField(max_length=30, blank=True, null=True)
	last_name = models.CharField(max_length=30)
	dob = models.DateField()
	c_image = models.ImageField()
	PARTY_AFFILIATE = (
		('Democratic', 'Democratic'),
		('Republican', 'Republican'),
		('Third Party', 'Third Party'),
		)
	party_affiliate = models.CharField(max_length=11, choices=PARTY_AFFILIATE)
	description = models.TextField();

	def get_absolute_url(self):
		return reverse('vote.views.candidates_detail', args=[str(self.c_id)])


	def __int__(self):
		return self.c_id

	def __str__(self):
		return ("%s %s %s"%(self.first_name, self.middle_name, self.last_name))


	class Meta:
		#preventing duplicates entry of candidates
		unique_together = ['first_name', 'last_name','dob']




	
class Election_Info(models.Model):
	e_id = models.AutoField(primary_key=True)
	#candidates_choice = models.ForeignKey(Candidates)
	CANDIDATES_CHOICE = (
		('Chris Choi', 'Chris Choi'),
		)
	candidates_choice = MultiSelectField(choices=CANDIDATES_CHOICE, max_length=50)
	e_name = models.CharField(max_length=100)
	e_description = models.TextField()
	YEAR_DROPDOWN =[]
	for y in range(2006, (datetime.datetime.now().year +5)):
		YEAR_DROPDOWN.append((y,y))
	year = models.IntegerField(choices=YEAR_DROPDOWN, default=datetime.datetime.now().year)

	POSITION_CHOICE = (('Precinct committeewoman, committeeman','Precinct committeewoman, committeeman'),
		('School Board Member/School Board President','School Board Member/School Board President'),
		('Township/Village Trustee/Town Council', 'Township/Village Trustee/Town Council'),
		('At-Large Councilwoman/man', 'At-Large Councilwoman/man'),
		('City Ward Councilwoman/man','City Ward Councilwoman/man'),
		('President of City Council', 'President of City Council'),
		('City Law Director', 'City Law DIrector'),
		('City Auditor', 'City Auditor'),
		('City Treasurer', 'City Treasurer'),
		('City Manager','City Manager'),
		('Clerk of Court', 'Clerk of Court'),
		('Common Pleas Court Judge','Common Pleas Court'),
		('County Recorder', 'County Recorder'),
		('County Coroner', 'County Coroner'),
		('County Prosecuting Attorney', 'County Prosecuting Attorney'),
		('County Treasurer', 'County Treasurer'),
		('County Engineer', 'County Engineer'),
		('County Auditor', 'County Auditor'),
		('County Executives', 'County Execitives'),
		('Board of County Commissioners', 'Board of County Comissioner'),
		('Democrat/Republican State Central Committee', 'Democrat/Republican State Central Committee'),
		('State Representative', 'State Representative'),
		('State Senator', 'State Senator'),
		)
	position = models.CharField(max_length=50, choices=POSITION_CHOICE)
	PRECINCT_CHOICE = []

	for x in range(50000,52809,101):
		code_x = x+1;
		code_y = code_x+100;
		pre_range = str(code_x) + " - " + str(code_y)

		PRECINCT_CHOICE.append((pre_range,pre_range))

	precincts_range = MultiSelectField(choices=PRECINCT_CHOICE)
	start_date = models.DateField()
	end_date = models.DateField()

	def __int__(self):
		return self.e_id


class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text






	
	

vote/views.py
from django.shortcuts import render,redirect, HttpResponseRedirect, get_object_or_404
from django.contrib.auth import(
	authenticate, 
	get_user_model,
	login,
	logout)
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.sessions.models import Session
from .forms import UserLoginForm, UserRegistrationForm, CandidatesForm, Election_InfoForm
from .models import Candidates, Election_Info, Question, Choice
from django.urls import reverse

''' for polling '''
def detail(request, question_id):
	user_name = get_username(request)
	u_id = get_uid(request)
	question = get_object_or_404(Question, pk=question_id)

	context = {
	'username': user_name,
	'u_id': u_id,
	'question': question,
	}

	return render(request, 'vote/detail.html', context)

def poll_list(request, u_id):
	user_name = get_username(request)
	#u_id = get_uid(request)
	latest_question_list = Question.objects.order_by('-pub_date')[:5]


	context = {
	'username': user_name,
	'u_id': u_id,
	'latest_question_list': latest_question_list,
	}	

	return render(request, 'vote/poll_list.html',
		context)


def results(request, question_id):
	#response = "You're looking at the results of question %s."
	#return HttpResponse(response % question_id)
	user_name = get_username(request)
	u_id = get_uid(request)
	question = get_object_or_404(Question, pk=question_id)
	context = {
	'username': user_name,
	'u_id': u_id,
	'question': question,
	}

	return render(request, 'vote/results.html',
		context)

def vote(request, question_id):
	#return HttpResponse("You're voting in question %s.")
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'vote/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()

		return HttpResponseRedirect(reverse('vote:results', args=(question.id,)))







# Create your views here.
def landing_view(request):
	user_name = get_username(request)
	u_id = get_uid(request)
	context = {
	'username': user_name,
	'u_id': u_id,
	}
	return render(request, 'vote/landing_page.html', context)

def login_view(request):
	title='Login'
	username=""
	form = UserLoginForm(request.POST or None)
	if form.is_valid():
		username = form.cleaned_data.get('username')
		password = form.cleaned_data.get('password')
		user = authenticate(username=username, password=password)
		request.session['user_name'] = user.username
		request.session['u_id'] = user.pk
		u_id = user.pk
		#print("primary key :" + str(u_id))
		if (user.is_staff):
			login(request, user)
			#return render(request, 'vote/welcome_staff.html', {'username':username})
			return redirect('/admin/staff/%s'% user.username)
		#print(request.user.is_authenticated())
		#return render(request,'vote/welcome.html', {'username':username})
		return redirect('/user/%s'% u_id)
	return render(request,'vote/login.html', {'form':form, 'title': title, 'username': username})

def candidates(request):
	if 'user_name' in request.session:
		user_name = request.session['user_name']
	else: 
		user_name = ""
	candidates = Candidates.objects.all()
	context = {
	'candidates': candidates,
	'title': 'Candidates list',
	'username': user_name
	}
	return render(request, 'vote/candidates_list.html', context)


def elections(request):
	user_name = get_username(request)
	elections = Election_Info.objects.all()
	context  = {
		'username': user_name,
		'elections': elections,
		'title': 'Election Forms'
	}
	return render(request, 'vote/election_list.html', context)


def staff_view(request, username):
	form = CandidatesForm()
	context = {
	'username':username,
	'form': form,
	}
	return render(request, 'vote/welcome_staff.html', context)

def user_view(request, u_id):
	user = get_object_or_404(User, pk=u_id)
	username = user.username
	u_id = user.pk
	context = {
	'username':username,
	'u_id': u_id
	}
	return render(request, 'vote/welcome_users.html', context)

def register_view(request):
	#print(request.user.is_authenticated())
	title = "Register"
	form = UserRegistrationForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		password = form.cleaned_data.get('password')
		user.set_password(password)
		new_user = authenticate(username=user.username, password=password)
		user.save()
		user.backend = 'django.contrib.auth.backends.ModelBackend'
		login(request, user)
		u_id=user.pk
		#print("user id = " + str(u_id))
		
		return render(request,'vote/welcome_users.html', {'username':user.username, 'u_id':u_id})
	
	user_name = get_username(request)
	context={
		'form': form, 
		'title': title,
		'username': user_name
	}
	return render(request, 'vote/registration_form.html', context)

def logout_view(request):
	logout(request)
	username = ""
	return render(request, 'vote/logout.html', {'username': username})

def post_candidates(request):
	if 'user_name' in request.session:
		user_name = request.session['user_name']
	else: 
		user_name = ""
	if request.method == 'POST':
		form = CandidatesForm(request.POST or None, request.FILES)
		if form.is_valid():
			candidate = form.save(commit=False)
			candidate.save()
			messages.success(request, "Successfully created!")
			#print(candidate.get_absolute_url())
			#return HttpResponseRedirect(candidate.get_absolute_url())
			context = {
			'button_action':'Update',
			}
			return redirect("/candidates_detail/%s/" % candidate.c_id, context)
		else: 
			print("form is not valid")
	else:
		form = CandidatesForm()
		username=""
		context={
			'form':form,
			'username': user_name,
			'button_action': 'Post' 
		}
	return render(request, 'vote/post_candidates.html', context)
	
def post_election(request):
	user_name = get_username(request)
	can_objs = Candidates.objects.all()
	
	if request.method  == 'POST':
		form = Election_InfoForm(request.POST or None)
		if form.is_valid():
			election = form.save(commit=False)
			election.save()
			messages.success(request, "Successfully created!")
			context = {
				'button_action':'Update',
			}
			return redirect("/admin/election_detail/%s/"%election.e_id)
		else:
			print("form is not valid")
	else:

		form = Election_InfoForm()
		context = {
			'username':user_name,
			'form':form,
			'button_action': 'Post',
			'can_objs': can_objs

		}
	return render(request, 'vote/post_election.html', context)# {'username':user_name,'form':form,'button_action': 'Post'})
	

def user_polls_view(request):
	election_info = Election_Info.objects.all()
	user_name = get_username(request)
	context={
		'username': user_name,
		'title': 'Polls',
		'election_info':election_info

	}
	return render('vote/users_view_poll.html', context) 


def election_detail(request, e_id):
	user_name = get_username(request)
	election_info = get_object_or_404(Election_Info, pk=e_id)
	candidates = election_info.candidates_choice
	precincts_range = election_info.precincts_range
	can_objs = Candidates.objects.all()
	name_list = []
	for can in can_objs:
		name = can.first_name +" " +can.last_name
		c_id = can.c_id
		name_list.append((name,c_id))

	context = {
		'username': user_name,
		'election_info': election_info,
		'candidates': candidates,
		'precincts_range': precincts_range,
		'name_list': name_list
	}
	return render(request, 'vote/election_detail.html', context)

def candidates_detail(request, c_id):

	if 'user_name' in request.session:
		user_name = request.session['user_name']
	else: 
		user_name = ""
	candidate_info = get_object_or_404(Candidates, pk=c_id)
	context = {
	'candidate_info':candidate_info,
	'username': user_name
	}
	return render(request, 'vote/candidates_detail.html', context)

	
def candidates_update(request, c_id=None):
	candidate = get_object_or_404(Candidates, pk=c_id)
	form = CandidatesForm(request.POST or None, instance=candidate )
	if form.is_valid():
		candidate = form.save(commit=False)
		candidate.save()
		messages.success(request, "Successfully updated!")
		return redirect("/candidates_detail/%s/" % candidate.c_id)

	user_name = get_username(request)

	context = {
	'username':user_name,
	'form': form 
	}
	return render(request, 'vote/post_candidates.html', context)

def election_update(request, e_id=None):
	election = get_object_or_404(Election_Info, pk=e_id)
	form = Election_InfoForm(request.POST or None, instance=election )
	if form.is_valid():
		election = form.save(commit=False)
		election.save()
		messages.success(request, "Successfully updated!")
		return redirect("/admin/election_detail/%s/" % election.e_id)

	user_name = get_username(request)

	context = {
	'username':user_name,
	'form': form 
	}
	return render(request, 'vote/post_election.html', context)

def user_info_update(request, u_id=None):
	user = get_object_or_404(User, pk=u_id)
	form = UserRegistrationForm(request.POST or None, instance=user)
	if form.is_valid():
		user = form.save(commit=False)
		user.save()
		messages.success(request, "Successfully updated!")
		return redirect("/user_info/%s/" % u_id)
	user_name = get_username(request)
	title = "Register"
	context = {
	'username':user_name,
	'form':form,
	'title': title,
	'u_id': u_id
	}
	return render(request, 'vote/user_update_form.html', context)

def user_info(request, u_id):
	user_info = get_object_or_404(User, pk=u_id)
	context={
		'u_id': u_id,
		'user_info': user_info,
		'username': user_info.username,
	}
	return render(request, 'vote/user_profile.html', context)

def get_uid(request):
	if 'u_id' in request.session:
		u_id = request.session['u_id']
		return u_id
	else:
		return None

def get_username(request):
	if 'user_name' in request.session:
		user_name = request.session['user_name']
		return user_name
	else: 
		user_name = ""
		return user_name

def candidate_delete_confirmation(request, c_id=None):
	user_name=get_username(request)
	candidate = get_object_or_404(Candidates, pk=c_id)
	context={
	'username': user_name,
	'candidate': candidate,

vote/templates/vote/base.html
{%load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>voteFSE</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://use.fontawesome.com/a00f86850a.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    
    <!--<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css'%}">-->
    <link rel="stylesheet" href="{% static 'css/main.css'%}">

    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
    <script src="{% static 'js/vendor/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>

    <!--Navbar-->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'vote:landing' %}">Election Webapp</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <li><a href="">{{ username|title}} </a></li>
         

        <li><a href="{% url 'vote:logout' %}">Logout  </a></li>
      </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
</head>
	{% block content %}
	{% endblock %}

</html>

vote/templates/vote/candidate_delete_success.html
{% extends 'vote/base_staff.html' %}
{% block content %}
<h4>You have successfully deleted candidate <b>{{first_name}} {{middle_name}} {{last_name}}</b></h4>

{% endblock %}

vote/templates/vote/candidates_list.html
{% extends 'vote/base_staff.html' %}
{% block content %}        
<div class="container">
    <div class="iconbox">
        <div class="col-md-12">
            <h3>{{title}}</h3>
            {% for candidate in candidates %}
                <div class="candidateinfo col-md-5">
                    <img src="{{candidate.c_image.url}}" class="img-responsive center-block" height="256" width="256">
                    <h4 class="text-center"><b>{{candidate.first_name}} {{candidate.middle_name}} {{candidate.last_name}}</b></h4>
                    <p class="text-center"><b>Party Affiliate: </b>{{candidate.party_affiliate}}</p>
                    <p class="text-center"><b>Date of birth: </b> {{candidate.dob}}</p>
                    <div class="text-center"><button type="submit" type="button" class="btn btn-info"><a href="{% url 'vote:candidates_detail' candidate.c_id %}" style="color:#ffffff">Edit Information</a></button></div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}
   
    

vote/templates/vote/detail.html
<h1>{{question.question_text}}</h1>
{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'vote:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{forloop.counter}}" value={{choice.id}} />
	<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br/>
{% endfor %}

<input type="submit" value="Vote"/>

</form>

vote/templates/vote/election_list.html
{% extends 'vote/base_staff.html' %}
{% block content %}        
    <div class="container">
    <div class="col-md-12">
         <h3>{{title}}</h3>
         {% for election in elections %}
         <div class="col-md-4">
          
          <p><b>Name: </b> {{election.e_name}}</p>
        <p><b>Description </b> {{election.e_description}}</p>
          
            
            <button type="sumbit" type="button" class="btn btn-info"><a href="{% url 'vote:election_detail' election.e_id %}" style="color:#ffffff">More</a></button>
             
         </div>
           {% endfor %}
          
         
          
    </div>
    </div>
{% endblock %}

vote/templates/vote/landing_page.html
{% extends 'vote/login_base.html' %}
{% block content %}
<!doctype html>
    <body>


    <div class="jumbotron">
      <div class="container">
        <h1 class="text-center">Your Vote Makes A Difference</h1>
          <div class="jumbotron_button text-center">        
              <p><a class="btn btn-primary btn-lg " href="{% url 'vote:login' %}" role="button">Get Started</a></p>
          </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-4 text-center">
            <i class="fa fa-check-square-o" aria-hidden="true"></i>
            <h2>Vote online within minutes</h2>
        </div>
        <div class="col-md-4 text-center">
            <i class="fa fa-television" aria-hidden="true"></i>
            <i class="fa fa-mobile" aria-hidden="true"></i>
            <h2>Submit your vote on your PC or mobile device</h2>
        </div>
        <div class="col-md-4 text-center">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
            <h2>View your voting history and past ballots</h2>
        </div>
      </div>
    </div>
       
    <div class="container-fluid">
        <div class="container text-center">
            <h1>Start Voting Today  </h1>
            <!--<h2>Sign Up Online </h2>-->
            <p><a class="btn btn-default btn-lg" href="{% url 'vote:register' %}" role="button"> Register Now</a></p>
        </div>
    </div>

    <hr>
      
    <div class="container">
      <footer>
        <p>Team 5</p>
      </footer>
    </div>
    
    </body>
</html>

{% endblock %}

vote/templates/vote/user_candidates_detail.html
{% extends 'vote/base_user.html' %}
{% block content %}        
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <p {% if message.tags == "success" %} class="alert alert-success" class="{{ message.tags }}"{% endif %}> {{message}} </p>
            {% endfor %}
        </ul>
    {% endif %}
    
    <div>
        <div class="col-md-12 candidateinfo">
            <div class="row">
                <img src="{{candidate_info.c_image.url}}" class="img-responsive center-block">
            </div>
            <div class="panel-heading text-center">
                <h3>{{candidate_info.first_name}} {{candidate_info.middle_name}} {{candidate_info.last_name}}</h3>
            </div>
            <p><b>Party affiliation: </b>{{candidate_info.party_affiliate}}
            <p><b>Date of birth: </b> {{candidate_info.dob}}</p>
            <p><b>Biography: </b>{{candidate_info.description}}</p>
            <div class='text-center'><button type="button" class="btn btn-info"><a href="{% url 'vote:view_candidates' u_id %}" style="color:#ffffff">Return</a></button></div>
        </div>
    </div>
{%endblock%}

vote/templates/vote/user_results.html
{% extends 'vote/base_user.html' %}
{% block content %}
  <h2>Results</h2>

{% endblock %}

vote/templates/vote/welcome_staff.html
{%load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>voteFSE</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://use.fontawesome.com/a00f86850a.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!--<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css'%}">-->
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
    <script src="{% static 'js/vendor/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>
</head>
    <!--Navbar-->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'vote:welcome_staff' username %}">Election Webapp</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <li><a href="{% url 'vote:welcome_staff' username %}">Hi {{ username|title}}!</a></li>
         
        <li><a href="{% url 'vote:logout' %}">Logout  </a></li>
      </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

<body>
	<div class="container">
		<div class="candidateinfo">
			<h2>Administrator Dashboard</h2>
		    <ul class="nav nav-pills nav-stacked" style="font-size:18px">
		        <li><a href="{% url 'vote:post_candidates' %}">Create Candidate</a></li>
		        <li><a href="{% url 'vote:candidates_list' %}">View/Edit Candidates</a></li>
		        <li><a href="{% url 'vote:post_election' %}">Create Election Poll</a></li>
		        <li><a href="{% url 'vote:elections_list' %}">View/Edit Election Polls</a></li>
		    </ul>
		</div>
	</div>
</body>

</html>